### ISSUE TITLE
Clarification on JavaScript support

### ISSUE THREAD

**Issue by dkurth** [kobolabs/epub-spec#11]
According to the section headed "JavaScript Support," Kobo for Android supports JS for fixed-layout content only, while iOS supports JS for both FXL and reflowable content.

Later, the "Support Grid" section indicates JS support on the eInk and desktop platforms.  Do these platforms support JS for both FXL and reflowable content, or just FXL?

Thanks!
Derek

**Comment by mramosch** [comment]
‘ eInk does partially support Javascript, we don't think the support is strong enough to suggest content creators expect it on those platforms ‘

That is very vague, unfortunately.

I am producing multi-lingual interactive epubs which work perfectly fine on many eReaders on Android and iOS. I could even get MediaOverlays to work in Apple Books by adding some custom JS code.

I am very disappointed that KOBO e-Ink devices don’t offer the possibility to let taps fall through their app-touch-layer and let my JS code take over.

I am being asked by so many language learners that would kill for not being forced to read their multi-lingual books on tablet and phone screens why my books don’t work on e-Ink devices.

I think KOBO is missing out here on many potential buyers.

Same is true for Audio Support. Instead of giving us that rather crapy pseudo book that in a hack-ish way lets us import some MP3 collection zip files, why not open up support for Audio objects and a little bit of JS.

I thought that KOBO (unlike Amazon) really cares about users and their experience, but it seems that they are like anyone else just trying to overly protect their own Audiobooks business.

What a shame…
