### ISSUE TITLE
Please clarify behavior of pop-up notes, and version support

### ISSUE THREAD

**Issue by tooolbox** [kobolabs/epub-spec#16]
Per your docs, [footnotes and endnotes are supported](https://github.com/kobolabs/epub-spec#footnotesendnotes-are-fully-supported-across-kobo-platforms), which is great!

There is the statement `Users of the eInk and iOS platforms (starting with version 7.3) see a pop-up text box containing a footnote or endnote’s text.`, but I'm not sure what "version 7.3" means.  Is this eInk firmware, or iOS app version?  Can this be differentiated, please?  For example, I have an old Kobo Touch, software version 3.11.0.  Could I expect the notes to pop up there?

What is the behavior of Kobo eReaders/apps if I were to use the `epub:type` attribute, and the reader was an older version that did not support this?

With iBooks, `epub:type` endnotes are not supported--only footnotes.  In other words, when you use hyperlinks with the `epub:type` attribute in iBooks, it will display a popover for that hyperlink, only if the target is in the same HTML file.  How does Kobo's behavior compare to this?

And overall, I want to make sure that I do, in fact, understand correctly that you "support the epub:type attribute", for example, in the way given detailed in [a blog post by Liz Castro](http://www.pigsgourdsandwikis.com/2012/05/creating-pop-up-footnotes-in-epub-3-and.html).  Please let me know if I misunderstood.

Finally, having this level of documentation on what Kobo supports and does not support is incredible, and a serious step up over other eBook distributors.  Way to go!

**Comment by bdugas** [comment]
The section on endnotes and footnotes has been updated to indicate that the pop-up feature exists on iOS and eInk. It will not work on the original Kobo reader or the Kobo WiFi but will work on the Touch and any eInk device released since. The version number 7.3 was for iOS but has the reference has been removed - anything up to date on either platform will have the feature.
Any Kobo app/device that does not support the pop-up will just take the user to the section being linked to.
The testing required to know which ePub:type attributes are supported across all Kobo platforms has not been conducted but the ePub:type "noteref" is supported on iOS. eInk does not read the "noteref" attribute but may in a future release. Both platforms have additional methods of detecting when linked content is a footnote or endnote and should display as a pop-up. Using "noteref" is the best way to ensure that iOS and future versions of other platforms will display footnote and endnote content as intended.
We very much appreciated the compliments. Many thanks :)
