### ISSUE TITLE
Can't sideload on Kobo App for testing purpose

### ISSUE THREAD

**Issue by marieBdesign** [kobolabs/epub-spec#19]
Hi,
I am an epub creator and want to sideload my epubs on a Galaxy tab (Android) for testing purposes. I have the Kobo App installed on it. Even if I follow the instructions on that sheet about sideloading, there is no import options appearing when I select options (the three dots on the top right), only "sync".

Same thing for Desktop App on Mac OS X. Can't make it work.

Thanks for any help.

Marie

**Comment by maliKobo** [comment]
For Android, you can access the import options from the three dots from the 'Reading List' section. To get to the Reading List, click on the 'Reading List' on the top-right area of the Kobo apps' home screen.

**Comment by marieBdesign** [comment]
Thank you, found it!
Can Kobo search onto the files on the tablet itself instead of only the SD Card?

**Comment by JayPanoz** [comment]
Since I know some people can't sideload a (fxl).kepub.epub file on OS X, count me in this thread.

The method described in the spec worked with ADE 3.0 but as soon as ADE 4 was released (and installed), it appeared broken and the epub file didn't sync anymore—it's broken for me and for a significant amount of people I know. 

You know that's a type of problem that would be easily solved with an import feature, right? 

I don't even care if I have to enable this feature with a command line (à la iBooks' inspector) in case you don't want to make it "public" but just help us do our work under proper conditions, please.

**Comment by wareid** [comment]
Hi @JayPanoz, some questions for you. 

I'll be looking into this issue for you tomorrow, but so I know what I'm trying to recreate, can you give me the version of OSX/KDA you are running, in case I need to escalate the issue. You are dropping the files to be sideloaded into the My Digital Editions folder in your documents, then going to KDA and entering Cmd+Shift+S? 

Thanks in advance,
Wendy
