### ISSUE TITLE
Improve sideload 

### ISSUE THREAD

**Issue by JayPanoz** [kobolabs/epub-spec#23]
Seriously, I'm doing my utmost to debug on your desktop and Android apps but proper tools are lacking.

1. the Android app scans all files, every time you try to import one, while sending a file from Dropbox to the Kobo app via the stock Android feature would be a million times easier—like **all other eBook apps do on Android**. And sometimes, for an unknown reason, it won’t find the only file you are trying to sideload or will fail importing it.
2. having to sideload via Adobe Digital Editions on desktop is like trying to cast a spell in an old language you don't speak, while dancing treble reel with the only troll who happens to know the exact location in the magic forrest where you should cast that spell in the first place. In other words, whatever I do, the file I add to ADE will **sync weeks or months after I sideload it, at the time I update the Kobo app.** It would obviously be too simple to add the file by drag and dropping it, sync must be earned. 

I know this is sounding really harsh but hey, if you don't provide us guys with simple tools which work, don't dare complain we don't QA/debug for your apps.

**Comment by bdugas** [comment]
Thanks Jay, the feedback is appreciated:
1. We have a user story for this already (ie. allow importing from outside the Kobo app). I've added your whole quote from that point to confirm that this feature would be valued from users such as yourself.
2. Are you trying to use ADE to get the content onto a non-Kobo eInk device? If not I'd suggest just dropping it directly onto your Kobo eInk device or dropping it into your My Digital Editions folder and importing to our Desktop app via the shortcut outlined [here](https://github.com/kobolabs/epub-spec#sideloading-for-testing-purposes). We are aware sideloading content onto ADE or onto a device through ADE is not particularly user friendly which is why we allow sideloading to our eInk devices and Desktop apps without going through it.

Harsh feedback is better than no feedback and we can never have too many people testing content on our apps.

**Comment by JayPanoz** [comment]
OK thanks, ⌘+SHIFT+S works as expected. BTW, is this a shortcut to force-sync?

**Comment by bdugas** [comment]
I just tested this and it looks like it only adds sideloaded content and does not sync your account.
