### ISSUE TITLE
[Kobo iOS] [Kobo Android] Publisher’s default + text-align 

### ISSUE THREAD

**Issue by JayPanoz** [kobolabs/epub-spec#28]
So, when text-align is not declared in the CSS and you pick “Publisher’s default” setting in the menu, the whole text is centered (by default).

For the record, if you set `text-align: left` for h1 for instance, then the whole text is left-aligned when using this setting. 

Applies to Kobo iOS and Kobo Android.

**Comment by bdugas** [comment]
Can you send a sample ePub or do you know of any files formatted in this way that are already in production? I'd be interested in testing in both environments.

**Comment by bdugas** [comment]
@JayPanoz just checking again to see if you have a sample? It would be difficult to scan our system specifically for a file with that CSS.

**Comment by JayPanoz** [comment]
Ok so there’s actually no need for a sample, the solution is actually pretty simple.

In my EPUB file I had: 

```
div {
  text-align: center;
}
```

And there was no `text-align` declaration for other selectors.

The assumption being: “well, I'm using `div` only for images so I don't need to attribute it a class.”

![photo 16-02-2017 12 48 33](https://cloud.githubusercontent.com/assets/12599652/23020405/411f51a2-f447-11e6-87d5-d1d08b52a869.png)

Since contents are appended in a div, `text-align: center` applies to the whole HTML file (1) when no `text-align` user setting is set.

When the user setting is set (2), `text-align` is set for `div#inner-book`.

That's probably an edge case but as far as I can remember, it's not the first time I encounter EPUB files in which such a prop is declared for a global element so I guess it's worth reporting it.

**Comment by bdugas** [comment]
@JayPanoz thanks for the follow up and the snippet. I'm not going to log this as a bug fix because 1) it is an edge case (we don't see this happen in any of the content we review) and 2) technically our app is doing what the content is telling it.
That said if we do see this display issue pop up in QA we'll refer back to this and see if we need to implement something on Android that will compensate for justification applied to the div tag.
