### ISSUE TITLE
simple navigation does not work as it should

### ISSUE THREAD

**Issue by spajak** [kobolabs/epub-spec#46]
Simple scenario with link `<a href="#foo">...</a>` to `<div id="foo">...</div>` somewhere else.
Clicking on the anchor always moves my ereader to the page BEFORE the page where `div#foo` is visible.
And if `id` is set on `<section>` or `<figure>` the landing page is even more "inaccurate".
My e-reader Clara HD (latest soft).

**Comment by wareid** [comment]
I'll take a look at this issue as well. When you look at the book are you sideloading it as .epub or .kepub.epub?

**Comment by spajak** [comment]
Its `.epub`. I will prepare a demo for all my issues

**Comment by spajak** [comment]
Please find my epub 3.2 demo here:
`https://mega.nz/#!oaQ1nIKY!Kzl_hZe4XW16ZjFTiCapoxjmHQ7EEQTa55EZAQL6E7A`
The above work well in Kindle (after kindlegen touch) as well as Calibre viewer. Tested on Clara HD (up to date soft).
Main issues I have are navigation (links) and sections. Please let me know if you find this demo might be improved.

**Comment by wareid** [comment]
Can you retest with the extension .kepub.epub? 

https://github.com/kobolabs/epub-spec#sideloading-for-testing-purposes

**Comment by spajak** [comment]
Hmm. now most of thinks aren't working...
Italics always bold (with Bookerly font). No CSS page-break-before on sections, TOC item points to a footnote.. No multiple sections in one xhtml support...
Please it looks perfect on Kindle (kindlegen).

Updated a link do my epub.

**Comment by wareid** [comment]
So we do have open issues regarding our support of page-break properties (there's a table listing it here: https://github.com/kobolabs/epub-spec#css) and that is a known issue.

The EPUB provided did not have bookerly referenced as a font, so I don't know what the problem is there. Publisher Default in this case I believe defaults to Georgia, which is our standard font. 

I don't understand the "multiple sections in one XHTML" support question, we are rendering the sections, and the text is present, anchors will bring you to them if they're not on the same page. 

TOC footnote, I will log as a bug as it looks like it's filling all of the backup requirements we set out for footnotes, but we need to possibly create a case where that should not occur if the reference is in a TOC.

**Comment by spajak** [comment]
I have sideloaded two fonts: Bookerly and Literata to sdcard. And the first one is set as my default font in the ereader. If I open my demo as `kepub.epub`, all italics are also bold in my default font - and this is not the case if I open it as just `epub`. So it behaves differently.

Sorry, by multiple sections i mean multiple chapters (`epub:chapter`). I have to investigate it better, maybe its because there are no page breaks..

**Comment by spajak** [comment]
The font problem (italic->bold) is moved to #49
